### ISSUE TITLE
[후원 회원가입 ] [뉴스레터] 플로팅 버튼

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/womenandwar#14]
https://stage.womenandwar.net/

기존홈 bottom에 있는 [후원 회원가입 ] [뉴스레터] 플로팅 버튼을 kfem 처럼 디자인 부탁드려요.

**Comment by calvin-design** [comment]
https://www.figma.com/file/MnajFO0PmnFqKTjvsyEYMr/WWM_0.1?node-id=1901%3A7264
