### ISSUE TITLE
메인 기획

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/womenandwar#3]
게시글의 정보성을 기준으로

**Comment by woonjjang** [comment]
https://docs.google.com/document/d/1pd6AQxDJPtGdQi6h13xHPLnwY35ZrqD9zDysUKMDX8U/edit

**Comment by woonjjang** [comment]
@calvin-design 오늘 저녁에나 원래 작업 기획서 전달할 수 있을 듯 해요. 지난번 회의를 바탕으로 피그마 테마에 메인 홈 하나 시작해 보세요. 

제가 이어서 기획화면 짜겠습니다.

**Comment by calvin-design** [comment]
간단한 기획화면을 짜보았습니다. 
https://www.figma.com/file/MnajFO0PmnFqKTjvsyEYMr/WWM_0.1?node-id=1504%3A6990
전쟁과여성 쪽에서 원하는 레이아웃이랑 래퍼런스 사이트랑 너무 차이가커서 어떤 디자인을 원하는 건지 확실하진 않지만, 일단은 직관, 정보 위주로 해서 모바일에서도 잘보일 수 있는 레이아웃으로 잡았습니다.

그리고 메뉴 개수에는 변화가 없을까요? 너무 길고 많은데요..
