### ISSUE TITLE
현재 폴더에 hugo project 시작

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/womenandwar#8]

**Comment by mozodev** [comment]
요것도 내일 같이 해보면 좋겠네요... 
프로젝트 새로 시작하는데 구조를 잘 모르면 곤란...
잘 모르면 각자 뭔가 만들때 계속 물어보고 싶어지겠죠? ㅎ

**Comment by woonjjang** [comment]
좋습니다. 완전 처음이라 DEV 쪽은 처음부터 논의를
