### ISSUE TITLE
게시글 MD 마이그레이션

### ISSUE THREAD

**Issue by mozodev** [team-durumi/womenandwar#9]
### 출발지 `extract`:

- 공지/보도자료  https://womenandwar.net/kr/notice/
- 자료실 https://womenandwar.net/kr/%ec%9e%90%eb%a3%8c%ec%8b%a4/
- 연대단체 활동소식 https://womenandwar.net/kr/%ec%97%b0%eb%8c%80%eb%8b%a8%ec%b2%b4-%ed%99%9c%eb%8f%99%ec%86%8c%ec%8b%9d/

###  맵핑? `transform`

`도착지 <= 출발지`

- 공지사항 <= 공지/보도자료:분류:공지
- 보도자료 <= 공지/보도자료:분류:보도자료
- 자료실 <= 
    * 공지/보도자료:분류:문서
    * 자료실:말머리:[수요시위 성명서] 
    * 자료실:분류:언론동향
    * 연대단체 활동소식

자료실 분류추가: 
- 본국상대소송
- 역사부정론 반박

### 도착지 `load`:

- 공지사항 https://stage.womenandwar.net/connect/notice/
- 보도자료 https://stage.womenandwar.net/connect/press-release/
- 자료실 https://stage.womenandwar.net/connect/resource/

**Comment by woonjjang** [comment]
### 출발지 `extract`:

- 활동보고 https://womenandwar.net/kr/%ed%99%9c%eb%8f%99%eb%b3%b4%ea%b3%a0/
- 공지/보도자료  https://womenandwar.net/kr/notice/
- 자료실 https://womenandwar.net/kr/%ec%9e%90%eb%a3%8c%ec%8b%a4/
- 연대단체 활동소식 https://womenandwar.net/kr/%ec%97%b0%eb%8c%80%eb%8b%a8%ec%b2%b4-%ed%99%9c%eb%8f%99%ec%86%8c%ec%8b%9d/

###  맵핑? `transform`

- source => target
### 공지/보도자료
- 활동보고 => 활동소개(post)
- 공지/보도자료 > 공지 => 공지사항
- 공지/보도자료 > 보도자료 => 보도자료
- 공지/보도자료 > 문서 => 자료실

### 자료실
- 자료실 에 [수요시위 성명서] 말머리 => 활동소개(post)>수요시위 > 성명서
- 자료실 > 언론동향 => 자료실 > 언론동향

### 연대단체 활동소식
- 연대단체 활동소식 => 자료실 

### 도착지 `load`:

- 공지사항 https://stage.womenandwar.net/connect/notice/
- 보도자료 https://stage.womenandwar.net/connect/press-release/
- 자료실 https://stage.womenandwar.net/connect/resource/
| - 언론동향
| - 일본국상대소송(분류추가)
| - 역사부정론 반박(분류추가)
| - 문서
| - 연대단체 활동소식
- 뉴스레터 https://stage.womenandwar.net/connect/newsletter/

**Comment by woonjjang** [comment]
레이아웃 붙이고 있어서 여러분의 지원이 필요합니다. 
화요일 - 고객 시연 예정되어 있습니다.

**Comment by mozodev** [comment]
https://drive.google.com/drive/folders/1y6nqjSe0_RpohcZVNSltuLPRQ_1IWAhZ

```
notice: 177
press: 246
resource: 205

# 공지/보도자료 id:1 게시판
- EMPTY: `17`
- 공지: `177`
- 문서: `8`
- 보도자료: `246`
```
